import { Platform } from "react-native";

export const Material3Baseline = {
  light: {
    primary: "#0B57D0",
    onPrimary: "#FFFFFF",
    primaryContainer: "#D3E3FD",
    onPrimaryContainer: "#041E49",
    inversePrimary: "#A8C7FA",
    secondary: "#00639B",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#C2E7FF",
    onSecondaryContainer: "#001D35",
    tertiary: "#006A6A",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#6FF7F7",
    onTertiaryContainer: "#002020",
    background: "#F8F9FA",
    onBackground: "#1F1F1F",
    surface: "#F8F9FA",
    onSurface: "#1F1F1F",
    surfaceVariant: "#E1E3E1",
    onSurfaceVariant: "#444746",
    surfaceTint: "#0B57D0",
    inverseSurface: "#303030",
    inverseOnSurface: "#F2F2F2",
    error: "#BA1A1A",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#410002",
    outline: "#747775",
    outlineVariant: "#C4C7C5",
    scrim: "#000000",
    surfaceBright: "#F8F9FA",
    surfaceDim: "#DADADA",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#F3F4F6",
    surfaceContainer: "#EDEDEE",
    surfaceContainerHigh: "#E7E8E9",
    surfaceContainerHighest: "#E1E2E4",
  },
  dark: {
    primary: "#A8C7FA",
    onPrimary: "#062E6F",
    primaryContainer: "#0842A0",
    onPrimaryContainer: "#D3E3FD",
    inversePrimary: "#0B57D0",
    secondary: "#7FCFFF",
    onSecondary: "#003355",
    secondaryContainer: "#004A77",
    onSecondaryContainer: "#C2E7FF",
    tertiary: "#4CDADA",
    onTertiary: "#003737",
    tertiaryContainer: "#004F4F",
    onTertiaryContainer: "#6FF7F7",
    background: "#111315",
    onBackground: "#E2E2E5",
    surface: "#111315",
    onSurface: "#E2E2E5",
    surfaceVariant: "#444746",
    onSurfaceVariant: "#C4C7C5",
    surfaceTint: "#A8C7FA",
    inverseSurface: "#E2E2E5",
    inverseOnSurface: "#1F1F1F",
    error: "#FFB4AB",
    onError: "#690005",
    errorContainer: "#93000A",
    onErrorContainer: "#FFDAD6",
    outline: "#8E918F",
    outlineVariant: "#444746",
    scrim: "#000000",
    surfaceBright: "#37393B",
    surfaceDim: "#111315",
    surfaceContainerLowest: "#0C0E10",
    surfaceContainerLow: "#191C1E",
    surfaceContainer: "#1E2022",
    surfaceContainerHigh: "#282A2D",
    surfaceContainerHighest: "#333538",
  },
} as const;

export type MaterialColorTheme = {
  [K in keyof typeof Material3Baseline.light]: string;
};

export const Elevation = {
  level0: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  level1: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    elevation: 1,
  },
  level2: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  level3: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 6,
  },
  level4: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
  },
  level5: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 12,
  },
};

export const Shapes = {
  none: 0,
  extraSmall: 4,
  small: 8,
  medium: 12,
  large: 16,
  extraLarge: 28,
  full: 9999,
};

export const Spacing = {
  half: 2,
  one: 4,
  two: 8,
  three: 12,
  four: 16,
  five: 20,
  six: 24,
  seven: 32,
  eight: 40,
  nine: 48,
  ten: 64,
};

export const Fonts = {
  displayLarge: {
    fontSize: 57,
    fontWeight: "400" as const,
    letterSpacing: -0.25,
    lineHeight: 64,
  },
  displayMedium: {
    fontSize: 45,
    fontWeight: "400" as const,
    letterSpacing: 0,
    lineHeight: 52,
  },
  displaySmall: {
    fontSize: 36,
    fontWeight: "400" as const,
    letterSpacing: 0,
    lineHeight: 44,
  },
  headlineLarge: {
    fontSize: 32,
    fontWeight: "400" as const,
    letterSpacing: 0,
    lineHeight: 40,
  },
  headlineMedium: {
    fontSize: 28,
    fontWeight: "400" as const,
    letterSpacing: 0,
    lineHeight: 36,
  },
  headlineSmall: {
    fontSize: 24,
    fontWeight: "400" as const,
    letterSpacing: 0,
    lineHeight: 32,
  },
  titleLarge: {
    fontSize: 22,
    fontWeight: "600" as const,
    letterSpacing: 0,
    lineHeight: 28,
  },
  titleMedium: {
    fontSize: 16,
    fontWeight: "600" as const,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  titleSmall: {
    fontSize: 14,
    fontWeight: "600" as const,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  bodyLarge: {
    fontSize: 16,
    fontWeight: "400" as const,
    letterSpacing: 0.5,
    lineHeight: 24,
  },
  bodyMedium: {
    fontSize: 14,
    fontWeight: "400" as const,
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  bodySmall: {
    fontSize: 12,
    fontWeight: "400" as const,
    letterSpacing: 0.4,
    lineHeight: 16,
  },
  labelLarge: {
    fontSize: 14,
    fontWeight: "600" as const,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelMedium: {
    fontSize: 12,
    fontWeight: "600" as const,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelSmall: {
    fontSize: 11,
    fontWeight: "600" as const,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
};

export const MaxContentWidth = 720;
